# Generated by Django 6.0 on 2026-01-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('carboidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('gorduras', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
