# Generated by Django 6.0 on 2026-01-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('idade', models.IntegerField()),
                ('atividade', models.CharField(max_length=20)),
                ('objetivo', models.CharField(max_length=20)),
                ('meta_calorica', models.FloatField()),
            ],
        ),
    ]
