# Generated by Django 6.0 on 2026-01-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacao', '0003_perfil_user_refeicao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='atividade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='meta_calorica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
