# Generated by Django 6.0 on 2026-01-31 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('atividade', models.CharField(choices=[('sedentario', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], default='sedentario', max_length=20)),
                ('objetivo', models.CharField(choices=[('perder', 'Perder peso'), ('manter', 'Manter peso'), ('ganhar', 'Ganhar peso')], default='manter', max_length=20)),
                ('meta_calorica', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
