# Generated by Django 6.0 on 2026-02-05 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='porcao',
            field=models.FloatField(default=100, help_text='Porção consumida em gramas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='carboidratos',
            field=models.FloatField(help_text='Carboidratos por 100g'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='gorduras',
            field=models.FloatField(help_text='Gorduras por 100g'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='proteinas',
            field=models.FloatField(help_text='Proteínas por 100g'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
