# Generated by Django 6.0 on 2026-03-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_refeicao_porcao_alter_refeicao_carboidratos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='quantidade',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='porcao',
            field=models.FloatField(help_text='Quantidade consumida em gramas'),
        ),
    ]
