# Generated by Django 6.0 on 2026-03-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0003_refeicao_quantidade_alter_refeicao_porcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='porcao',
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='carboidratos',
            field=models.FloatField(blank=True, help_text='Carboidratos por 100g', null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='gorduras',
            field=models.FloatField(blank=True, help_text='Gorduras por 100g', null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='proteinas',
            field=models.FloatField(blank=True, help_text='Proteínas por 100g', null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='quantidade',
            field=models.FloatField(help_text='Quantidade consumida em gramas'),
        ),
    ]
