# Generated by Django 6.0 on 2026-03-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0004_remove_refeicao_porcao_alter_refeicao_carboidratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='carboidratos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='gorduras',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='proteinas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='quantidade',
            field=models.FloatField(),
        ),
    ]
